import Head from "next/head";
import { About, Contact, Main, NavBar, Projects, Skills } from "@/components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nguyen Khanh Vinh | FullStack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
